keys:
  - &admin_john age1stq425283tespjml4a6w28g582jl8a5wdnl97akjnhu2cufayfjst4xvyh
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *admin_john
  - path_regex: secrets/john/[^/]+\.yaml$
    key_groups:
    - age:
      - *admin_john
